### YamlMime:UniversalReference
items:
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode:enum'
    summary: |-
      Códigos de error de las funciones personalizadas. Los códigos de error aparecerán en la celda que invocó la función.

      Aparecen mensajes de error personalizados además de estos códigos de error. Los mensajes personalizados se muestran en el menú indicador de error, al que se tiene acceso al mantener el puntero sobre el indicador de error en cada celda con un error.
    name: CustomFunctions.ErrorCode
    fullName: CustomFunctions.ErrorCode
    langs:
      - typeScript
    type: enum
    package: custom-functions-runtime!
    children:
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.divisionByZero:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidName:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidNumber:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidReference:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidValue:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.notAvailable:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.nullReference:member'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.divisionByZero:member'
    summary: 'Este código de error indica que la función usada está dividiendo por cero o celdas vacías. No se puede usar un mensaje de error personalizado. \[[Conjunto de API: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: divisionByZero
    fullName: divisionByZero
    langs:
      - typeScript
    type: field
    numericValue: '"#DIV/0!"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidName:member'
    summary: 'Este código de error indica que hay un error tipográfico en el nombre de la función. Tenga en cuenta que este código de error se admite como un error de entrada de función personalizada, pero no como un error de salida de función personalizada. No se puede usar un mensaje de error personalizado. \[[Conjunto de API: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: invalidName
    fullName: invalidName
    langs:
      - typeScript
    type: field
    numericValue: '"#NAME?"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidNumber:member'
    summary: 'Este código de error indica que hay un problema con un número en la función. No se puede usar un mensaje de error personalizado. \[[Conjunto de API: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: invalidNumber
    fullName: invalidNumber
    langs:
      - typeScript
    type: field
    numericValue: '"#NUM!"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidReference:member'
    summary: 'Este código de error indica que la función hace referencia a una celda no válida. Tenga en cuenta que este código de error se admite como un error de entrada de función personalizada, pero no como un error de salida de función personalizada. No se puede usar un mensaje de error personalizado. \[[Conjunto de API: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: invalidReference
    fullName: invalidReference
    langs:
      - typeScript
    type: field
    numericValue: '"#REF!"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidValue:member'
    summary: 'Este código de error indica que un valor de la función es del tipo de datos incorrecto. Si lo desea, puede usar un mensaje de error personalizado además del código de error. \[[Conjunto de API: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: invalidValue
    fullName: invalidValue
    langs:
      - typeScript
    type: field
    numericValue: '"#VALUE!"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.notAvailable:member'
    summary: 'Este código de error indica que la función o el servicio no está disponible. Si lo desea, puede usar un mensaje de error personalizado además del código de error. \[[Conjunto de API: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: notAvailable
    fullName: notAvailable
    langs:
      - typeScript
    type: field
    numericValue: '"#N/A"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.nullReference:member'
    summary: 'Este código de error indica que los intervalos de la función no se entrecruzan. No se puede usar un mensaje de error personalizado. \[[Conjunto de API: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: nullReference
    fullName: nullReference
    langs:
      - typeScript
    type: field
    numericValue: '"#NULL!"'